import fs from 'node:fs';
import path from 'node:path';
import { bilingualGuideSchema, isPublishableGuide } from '../src/content-guide-schema';

const CONTENT_DIR = path.resolve(process.cwd(), 'content/test-guides');
const OUTPUT_FILE = path.resolve(process.cwd(), 'src/data/approvedGuideManifest.ts');

export interface PublishedGuideRecord {
  slug: string;
  titleEn: string;
  titleHi: string;
  summaryEn: string;
  summaryHi: string;
  englishContent: string;
  hindiContent: string;
  citations: Array<{ id: string; title: string; url: string; accessedAt: string }>;
  price?: { customerPriceInr: number; listedValueInr: number };
  lastReviewedAt: string;
}

function readGuideRecords(directory: string): PublishedGuideRecord[] {
  if (!fs.existsSync(directory)) return [];

  const records: PublishedGuideRecord[] = [];
  for (const entry of fs.readdirSync(directory, { withFileTypes: true }).filter((item) => item.isDirectory()).sort((a, b) => a.name.localeCompare(b.name))) {
    const file = `${entry.name}/guide.json`;
    const metadataPath = path.join(directory, entry.name, 'guide.json');
    if (!fs.existsSync(metadataPath)) throw new Error(`${file}: guide.json is required`);
    const source = JSON.parse(fs.readFileSync(metadataPath, 'utf8'));
    const parsed = bilingualGuideSchema.safeParse(source);
    if (!parsed.success) {
      throw new Error(`${file}: ${parsed.error.issues.map((issue) => issue.message).join('; ')}`);
    }
    if (parsed.data.slug !== entry.name) {
      throw new Error(`${file}: slug must match its guide directory`);
    }
    if (!isPublishableGuide(parsed.data)) continue;

    const expectedEnglishPath = `content/test-guides/${entry.name}/en.md`;
    const expectedHindiPath = `content/test-guides/${entry.name}/hi.md`;
    if (parsed.data.englishPath !== expectedEnglishPath || parsed.data.hindiPath !== expectedHindiPath) {
      throw new Error(`${file}: language paths must point to this guide directory`);
    }

    const englishPath = path.resolve(process.cwd(), parsed.data.englishPath);
    const hindiPath = path.resolve(process.cwd(), parsed.data.hindiPath);
    if (!fs.existsSync(englishPath) || !fs.existsSync(hindiPath)) {
      throw new Error(`${file}: approved guide is missing its English or Hindi Markdown file`);
    }

    const englishContent = fs.readFileSync(englishPath, 'utf8').trim();
    const hindiContent = fs.readFileSync(hindiPath, 'utf8').trim();
    if (!englishContent || !hindiContent) throw new Error(`${file}: bilingual Markdown content cannot be empty`);

    records.push({
      slug: parsed.data.slug,
      titleEn: parsed.data.titleEn,
      titleHi: parsed.data.titleHi,
      summaryEn: parsed.data.summaryEn,
      summaryHi: parsed.data.summaryHi,
      englishContent,
      hindiContent,
      citations: parsed.data.citations,
      price: parsed.data.price,
      lastReviewedAt: parsed.data.lastReviewedAt,
    });
  }
  return records;
}

export function buildGuideManifest(directory = CONTENT_DIR, outputFile = OUTPUT_FILE) {
  const records = readGuideRecords(directory);
  fs.mkdirSync(path.dirname(outputFile), { recursive: true });
  fs.writeFileSync(
    outputFile,
    `// Generated by scripts/build-guide-manifest.ts. Do not edit manually.\nexport interface ApprovedGuideRecord {\n  slug: string;\n  titleEn: string;\n  titleHi: string;\n  summaryEn: string;\n  summaryHi: string;\n  englishContent: string;\n  hindiContent: string;\n  citations: Array<{ id: string; title: string; url: string; accessedAt: string }>;\n  price?: { customerPriceInr: number; listedValueInr: number };\n  lastReviewedAt: string;\n}\n\nexport const approvedGuideManifest: ApprovedGuideRecord[] = ${JSON.stringify(records, null, 2)};\n`,
    'utf8',
  );
  return records;
}

if (process.argv[1]?.endsWith('build-guide-manifest.ts')) {
  const records = buildGuideManifest();
  console.log(`Built approved guide manifest: ${records.length} guide(s).`);
}
