// Generated by scripts/build-guide-manifest.ts. Do not edit manually.
export interface ApprovedGuideRecord {
  slug: string;
  titleEn: string;
  titleHi: string;
  summaryEn: string;
  summaryHi: string;
  englishContent: string;
  hindiContent: string;
  citations: Array<{ id: string; title: string; url: string; accessedAt: string }>;
  price?: { customerPriceInr: number; listedValueInr: number };
  lastReviewedAt: string;
}

export const approvedGuideManifest: ApprovedGuideRecord[] = [];
